name: PublishToNpm

on:
  push:
    branches: [publish-ssy-ui-vite]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.8.0
      - run: pnpm install
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.CREAT_SSY_TOKEN }}
